### ISSUE TITLE
Mobile (Android) Keyboard Remains Open after Enter/Next Tapped

### ISSUE THREAD

**Issue by briancodes** [ngxtools/ngx.tools#11]
On mobile browser, Android (Chrome v67) after entering search text and tapping Next (Enter/RightArrow) on the soft keyboard, the keyboard remains open

**Expected:**
- The keyboard should close when next/enter tapped

**Note:**
You could possibly add the Search input to a Form, and add a 'submit' event listener. That should be triggered by the mobile keyboard enter/next, and then call `blur()` on the target - [StackBlitz](https://stackblitz.com/edit/mobile-keyboard-close) tested with Android Chrome

**Comment by manekinekko** [comment]
thanks @briancodes I'll add this to my todo list ;)
