### ISSUE TITLE
Implement an Infinite scroll pagination

### ISSUE THREAD

**Issue by manekinekko** [ngxtools/ngx.tools#13]
We want similar behavior:
![](https://user-images.githubusercontent.com/1699357/38998317-9817e1d8-43ef-11e8-958d-2601e233e95b.gif)

See directive code: https://github.com/sfeir-open-source/angular-search-experience/blob/master/src/app/search-ui/search/infinite-scroll.directive.ts

The directive is used here: https://github.com/sfeir-open-source/angular-search-experience/blob/master/src/app/search-ui/search/search.component.html#L1

**Comment by parsyval** [comment]
I'm on it if that's ok.

**Comment by manekinekko** [comment]
Closed by #15
