### ISSUE TITLE
Img display issue on mat-button, overflow scroll on card content

### ISSUE THREAD

**Issue by Daynil** [ngxtools/ngx.tools#2]
Not sure exactly why i'm having these particular issues, but the img within the mat-buttons for the github icon and npm icon are being blown out to 100% width within card search results:
![image](https://user-images.githubusercontent.com/4650666/39160253-da0dfa3a-472f-11e8-84fa-b0b0dd28162c.png)

The ligature-based buttons have no issue.

img's have a global style of position: fixed and width: 100%. When I remove these two properties, display works as expected.

Additionally, .mat-card-content contains overflow of scroll, and the scroll bars are showing up. This seems to be resolved by removing overflow: scroll.

I'm on chrome, but it happens on firefox and edge for me as well.

Very cool tool!

**Comment by Hongbo-Miao** [comment]
Same here

**Comment by manekinekko** [comment]
Thanks for the feedback. I've fixed the image issues.

Looking into the scroll issue next.

**Comment by manekinekko** [comment]
the scroll issue should be fixed by now. But it seems that Edge shows the Y scroll bar by default when `overflow-y` is set. I don't have a Windows machine to debug this issue in depth.

**Comment by manekinekko** [comment]
Please open a new issue if you believe the issue wasn't fixed.
