### ISSUE TITLE
The app freezes while loading (on new deploys)

### ISSUE THREAD

**Issue by yasselavila** [ngxtools/ngx.tools#23]
**Describe the bug**
The application freezes while loading (in Firefox)

**To Reproduce**
1. Go to 'https://ngx.tools'
2. App dies while loading...

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Firefox
 - Version: 63 & 64b

**Additional context**
Notice it only happens with new versions of the app... if you make a full reload (ctrl+f5) the app starts working as expected...

**Comment by manekinekko** [comment]
to fix this issue, please refer to issue #24
