### ISSUE TITLE
Improve the PWA experience

### ISSUE THREAD

**Issue by manekinekko** [ngxtools/ngx.tools#24]
The current PWA configuration is unstable. The server worker seems not to cache all resources, which causes the app to break and gets stuck in the loading UI.

Related bug #23

**Comment by thanhpd** [comment]
Can I take a look at this? Thanks.

**Comment by thanhpd** [comment]
It's weird, I cannot reproduce the problem that was mentioned in #23 with the same system/browser. The app loaded fine for me the first time.
However, whenever I tried to go to the app in offline mode it got stuck at the loading screen. For that, I believe there was https://github.com/ngxtools/ngx.tools/pull/25 but I'm not sure if that has resolved the problem fully. I've tried the solution on Netlify but it's not working on offline mode.

**Comment by fidele137** [comment]
Did you include a --prod flag when building ? If not, the ServiceWorker won't be included. I tried it and it seems to work offline :)

**Comment by fidele137** [comment]
Did you include the --prod flag when building? If not the service worker won't be included. The #25 fixes the white screen problem for me when I tested locally. However the app can't totally be used offline because it depends on Algolia services I think

**Comment by manekinekko** [comment]
thanks, guys for taking this issue. Could you go even further and notify the users of any available new updates? See the docs here: https://angular.io/guide/service-worker-communications#available-and-activated-updates

**Comment by fidele137** [comment]
I have already dealt with that, I can take that :)

**Comment by fidele137** [comment]
#27 fix this issue I think, waiting for the confirmation

**Comment by manekinekko** [comment]
The root cause of this was actually coming from the firebase cache-control configuration. 
It should be fixed by now.
