### ISSUE TITLE
Virtual Scroll problems

### ISSUE THREAD

**Issue by LouisAugry** [ngxtools/ngx.tools#29]
**Describe the bug**
When you are on the bottom of the page, the virtual scroll take the control and scrolls it infinitely

**To Reproduce**
1. Go to https://ngx.tools/#/search
2. Click on the search bar and type something
3. Scroll down to the bottom of the page
4. And it's scrolling without any action of your part

**Expected behavior**
Expect to have the control of the virtual scroll

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome

**Comment by HZooly** [comment]
Happens on Chrome Windows 10 too 👀
