### ISSUE TITLE
Results search not appears after no packages found

### ISSUE THREAD

**Issue by HZooly** [ngxtools/ngx.tools#30]
**Describe the bug**
If you get no result, you arrive on this view.

![image](https://user-images.githubusercontent.com/7328625/52330026-9c25e900-29f4-11e9-893e-e2bb0f21d609.png)

If you do a new search, nothing will appear, Not found view will stay.

In network tab, I can see results from Algolia, so I think it's a client error.

**To Reproduce**
1. Search for unknown packages : `datepicker-not-found`
2. No result appears
3. Search for existing packages : `datepicker`

**Expected behavior**
Get a new results list.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version 0.59.34 Chromium: 72.0.3626.81

**Comment by manekinekko** [comment]
could you please do a hard refresh and try again. we experienced a bad issue with firebase caching during the last deploy.

**Comment by LouisAugry** [comment]
Cant reproduce for my part

**Comment by HZooly** [comment]
![image](https://user-images.githubusercontent.com/7328625/52343336-15830300-2a18-11e9-8fb6-83a8990f03e7.png)

Still have an empty list

**Comment by HZooly** [comment]
Ok after some tests, it clearly comes from my browser (Brave). Tested on Chrome, expected behavior.

**Comment by HZooly** [comment]
Last update @manekinekko 

Disabling Brave Shield "unlock" the search results, no idea why at the moment.

![image](https://user-images.githubusercontent.com/7328625/52356246-2e011680-2a34-11e9-8223-fbd360ea093b.png)

**Comment by manekinekko** [comment]
That's interesting. I'd like to have more details about this if you can share some logs et traces. Cheers.

**Comment by HZooly** [comment]
What I can see is that when Brave shield is enabled, once the "No packages found" appears, there's an error about Analytics in the console : 

`ERROR TypeError: window.ga is not a function`

**Comment by manekinekko** [comment]
Oh I see. That's Google Analytics script. Thanks for reporting this.
