### ISSUE TITLE
@collab-ui/angular is not found 

### ISSUE THREAD

**Issue by mohammedzamakhan** [ngxtools/ngx.tools#32]
When I search for @collab-ui/angular, I do not find it available in ngx.tools, it even has a schematic available for it

https://www.npmjs.com/package/@collab-ui/angular

**Comment by manekinekko** [comment]
Hi, this package isn't showing up in the results because it is missing the required keywords `ngx` and `angular` in the [package.json](https://github.com/collab-ui/collab-ui-angular/blob/master/package.json).

**Comment by mohammedzamakhan** [comment]
Thats confusing, because I see [ngx-loadable](https://github.com/mohammedzamakhan/ngx-loadable/blob/master/package.json) in the search results even though it only has `ngx` in the name, and has no keywords. 

This @collab-ui/angular's package json has angular in its `name` too, so does it want it to start with angular?

**Comment by manekinekko** [comment]
@Haroenv could you please provide a quick explanation on how the ranking algorithm at Algolia is applied to the results for this situation?

**Comment by manekinekko** [comment]
@mohammedzamakhan I'm confused as well because the response we get from the backend has the `keywords` entry.

![image](https://user-images.githubusercontent.com/1699357/53728884-02771d80-3e74-11e9-82c8-f7a93d5066a4.png)

**Comment by Haroenv** [comment]
`(keywords:ngx OR keywords:angular) AND (NOT keywords:angularjs)` this is the filter you are sending, meaning that something will only be shown here in ngx.tools if it has keywords. 

A change can be made in these filters to also add things that start with `ngx` or `angular`, which makes sense to me, but naming conventions are always tricky

**Comment by mohammedzamakhan** [comment]
I found the keywords in ngx-loadable. Thanks for the help
