### ISSUE TITLE
ngx.tools doesn't load the angular application. Site displays loading icon

### ISSUE THREAD

**Issue by chihab** [ngxtools/ngx.tools#33]
**Describe the bug**
ngx.tools doesn't load the angular application. Site displays loading icon

**To Reproduce**
I haven't been able to reproduce the issue in a private browsing window. I guess the behavior is related to my browser state: installed SW / cached assets... I hope, I am the only one facing it.

1. Go to 'ngx.tools'
2. loading icon displayed, error in console
```
Failed to load ‘https://ngx.tools/main.94a18d1d57f0cd44f36e.js’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘Error: Response not Ok (fetchAndCacheOnce): request for https://ngx.tools/main.94a18d1d57f0cd44f36e.js returned response 404 Not Found’. ngsw-worker.js:589:31
```
```
<app-root>
    <img src="assets/loading.svg" alt="loading" class="loading">
  </app-root>
```
3. Hit refresh
4. Same issue with the same error in console
5. Hit cmd + shift + r
6. Home page is displayed. Console displays:  `check for updates?`

**Expected behavior**
Load Angular app, display home page

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Firefox
 - Version: 68

**Comment by manekinekko** [comment]
Hi, can you still reproduce this issue with the latest release?

**Comment by chihab** [comment]
No. Closing then.
