### ISSUE TITLE
Contributions accepted?

### ISSUE THREAD

**Issue by tayambamwanza** [ngxtools/ngx.tools#39]
Hi this is just a quick question, are you open to accepting contributions? I feel like this tool will become invaluable for third party libraries updating to latest angular features :).

Let me know I'd like to contribute when I have time in the future.

**Comment by manekinekko** [comment]
Hi @tayambamwanza this is a full open source projects. All contributions are welcome 👍

**Comment by tayambamwanza** [comment]
Thank you
