### ISSUE TITLE
Colours

### ISSUE THREAD

**Issue by NashPL** [ngxtools/ngx.tools#5]
As a person who has to problems with eyes. The colour of a page is too bright and bold. Makes my eyes not feeling comfortable. Mabe an option to change the colour schemas would be nice.

**Comment by manekinekko** [comment]
Good idea. Could you please provide any resources about the right colour scheme to use for this case? It will help implement this feature rapidly.

**Comment by NashPL** [comment]
I would stick to standards, Possible white and black to start off but you can offer other colour schemas. 
I usually feel more comfortable with dark colour background and text colour which will contrast well with the environment. 
I recommend reading this document for more information 
https://www.viget.com/articles/color-contrast/

**Comment by manekinekko** [comment]
done. check the new update.
